export const MODAL = {
    OPEN_MODAL: "SHOW_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL"
    /* OPEN_MODAL_SELECT: "OPEN_MODAL_SELECT",
    OPEN_MODAL_CREATE: "OPEN_MODAL_CREATE",
    SET_MODE_UPDATE: "SET_MODE_UPDATE",
    CLOSE_MODAL: "CLOSE_MODAL",
    SET_TYPE_FILE: "SET_TYPE_FILE",
    SET_TYPE_FOLDER: "SET_TYPE_FOLDER"   */      
}