
export const FILE = {
    ADD_FILE: "ADD_FILE",
    REMOVE_FILE: "REMOVE_FILE",
    OPEN_INNER_FILE: "OPEN_INNER_FILE",
    GET_FILES: "GET_FILES",
    SET_FILES: "SET_FILES",
    GET_FILE_ID: "GET_FILE_ID",
    SET_FILE_ID: "SET_FILE_ID",
    FETCH_FILE_FAILED: "FETCH_FILE_FAILED"
}