    export const FILE = {
    SET_TYPE_FILE: "SET_TYPE_FILE",
    ADD_FILE: "ADD_FILE",    
    GET_FILES: "GET_FILES",
    SET_FILES: "SET_FILES",
    GET_FILE_ID: "GET_FILE_ID",
    SET_FILE_ID: "SET_FILE_ID",
    SET_ACTIVE_FILE: "SET_ACTIVE_FILE",
    // FETCH_FILE_FAILED: "FETCH_FILE_FAILED",
    REMOVE_FILE: "REMOVE_FILE",
    OPEN_INNER_FILE: "OPEN_INNER_FILE"
}