export const FOLDER = {
    SET_TYPE_FOLDER: "SET_TYPE_FOLDER",
    ADD_FOLDER: "ADD_FOLDER",        
    GET_FOLDERS: "GET_FOLDERS",
    SET_FOLDERS: "SET_FOLDERS",
    GET_FOLDER_ID: "GET_FOLDER_ID",
    SET_FOLDER_ID: "SET_FOLDER_ID",
    SET_ACTIVE_FOLDER: "SET_ACTIVE_FOLDER",
    FETCH_FOLDER_FAILED: "FETCH_FOLDER_FAILED",
    REMOVE_FOLDER: "REMOVE_FOLDER",
    OPEN_INNER_FOLDER: "OPEN_INNER_FOLDER"
}