export const FOLDER = {
    // SAVE_FOLDER: "SAVE_FOLDER",
        
    GET_FOLDERS: "GET_FOLDERS",
    SET_FOLDERS: "SET_FOLDERS",
    GET_FOLDER_ID: "GET_FOLDER_ID",
    SET_FOLDER_ID: "SET_FOLDER_ID",
    FETCH_FOLDER_FAILED: "FETCH_FOLDER_FAILED",
    REMOVE_FOLDER: "REMOVE_FOLDER",
    OPEN_INNER_FOLDER: "OPEN_INNER_FOLDER"
}